# sonar-project.properties

sonar.projectKey=Rainnnnnnnn-maker_toeic_website_ver2.0
sonar.organization=rainnnnnnnn-maker

# スキャン対象
sonar.sources=src
sonar.exclusions=**/*.test.ts,**/*.spec.ts,**/node_modules/**,**/.next/**,**/coverage/**,**/public/**

# テストファイル
sonar.tests=src
sonar.test.inclusions=src/lib/(tests)/**/*.test.ts

# TypeScript
sonar.typescript.tsconfigPath=tsconfig.json

# カバレッジ（手順4実施済み）
sonar.javascript.lcov.reportPaths=coverage/lcov.info
